# Generated by Django 5.2.8 on 2026-03-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('indie', 'Indie'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('pixel graphics', 'Pixel Graphics'), ('horror', 'Horror'), ('metroidvania', 'Metroidvania')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
