# Generated by Django 5.2.8 on 2026-03-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
