# Generated by Django 6.0.2 on 2026-03-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_product_genre'),
        ('products', '0005_product_price'),
    ]

    operations = [
    ]
