# Generated by Django 5.2.8 on 2026-03-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_product_genre'),
        ('products', '0005_product_price'),
    ]

    operations = [
    ]
