# Generated by Django 5.2.8 on 2026-03-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20260308_1933'),
        ('products', '0006_merge_20260309_1631'),
    ]

    operations = [
    ]
