# Generated by Django 5.2.8 on 2026-03-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
